### ISSUE TITLE
Issue with MySQLConnection

### ISSUE THREAD

**Issue by leffraytheo** [SamuelAl/SQuelized-for-Processing#1]
Hey,
i'm new to databases and MySQL and i would like to use SQuelized to create a little tool on Processing.
I created a MySQL database, but i definetly can't connect to the database on processing using the method on the SQuelized website. 

Here is my code :

`import samuelal.squelized.*;

void setup() {
  
  SQLConnection connection = new MySQLConnection("root", "", "jdbc:mysql://localhost:3306/archibase");
  Table testTable = connection.getTable("personnes");
  printTable(testTable);
}

void printTable(Table table) {

  for (TableRow row : table.rows())
  {
    for (int i = 0; i < row.getColumnCount(); i++)
    {
      System.out.print(row.getString(i) + "  ");
    }
    System.out.println();
  }
}
`

and the error i'm getting. 

`SQuelized 1.0.0 by Samuel Alarco Cantos https://samuelal.github.io/squelized.github.io/index.html
Connection failed
The server time zone value 'Paris, Madrid' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
Connected as to jdbc:mysql://localhost/archibase
NullPointerException
`

Thank you in advance !

**Comment by SamuelAl** [comment]
Hi!
I am glad to see you have started experimenting with SQuelized. The error you show me is quite typical of MySQL and is usually due to a conflict between OS timezone and database configuration timezone. The specific solution depends a lot on the database you are trying to connect to, but adding these extra properties to the URL might help to do the trick: "?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
As an example, consider:
"jdbc:mysql://localhost:3306/myDatabase?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
Hope it helps! Otherwise you might have to change your database configuration, but that has to be done on your MySQL server.

**Comment by leffraytheo** [comment]
Everything is working ! Thank you very much for your answer and for the library, it's very helpful !
Have a nice day
